### PR TITLE
Readme and template

### LINKED ISSUE #35: Prepare template and readme in order to handoff for documentation

### PR DESCRIPTION
**Pull request by fabriziovigevani**
closes #35

Includes basic instructions to run Lock app locally with the template.

### CODE REVIEW

**Comment by burrrata** [comment]
Works on my machine!
- tried `npm run start:template` => failed building front-end
- ran `npm i` then `npm audit fix`
- tried `npm run start:template` again => worked!

**Comment by fabriziovigevani** [comment]
Yes!

Will have to update the upper box on a new branch. If you see everything ok in the README i'll go ahead and merge this.

**Comment by burrrata** [comment]
Actually I've noticed that when I create a vote, lock tokens, and then click the "withdraw" button in the lock app the screen just goes blank. Is that one of the issues that you're in the process of resolving?

**Comment by fabriziovigevani** [comment]
Yes that is resolved in the branch i work on. 

I will merge this and then merge the other one

**Pull request merged**
